PACKET_DEFS = {
  # [Packet ID, Name, ClientToServer, ServerToClient]
  0x00 => ['NoOp', nil, nil],
  0x01 => ['LoginRequest', {
    version: :int,
    username: :string,
    password: :string,
    map_seed: :long,
    dimension: :byte,
  }, {
    entity_id: :int,
    unknown1: :string,
    unknown2: :string,
    map_seed: :long,
    dimension: :byte,
  }],
  0x02 => ['Handshake', {
    username: :string,
  },
  {
    connection_hash: :string,
  }],
  0x03 => ['ChatMessage', {
    message: :string,
  }, {
    message: :string,
  }],
  0x04 => ['TimeUpdate'],
  0x05 => ['EntityEquipment'],
  0x06 => ['SpawnPosition'],
  0x07 => ['UseEntity'],
  0x08 => ['UpdateHealth'],
  0x09 => ['Respawn'],
  0x0A => ['Player'],
  0x0B => ['PlayerPosition'],
  0x0C => ['PlayerLook'],
  0x0D => ['PlayerPositionAndLook'],
  0x0E => ['PlayerDigging'],
  0x0F => ['PlayerBlockPlacement'],
  0x10 => ['HoldingChange'],
  0x11 => ['UseBed'],
  0x12 => ['Animation'],
  0x13 => ['EntityAction'],
  0x14 => ['NamedEntitySpawn'],
  0x15 => ['PickupSpawn'],
  0x16 => ['CollectItem'],
  0x17 => ['AddObject'],
  0x18 => ['MobSpawn'],
  0x19 => ['EntityPainting'],
  0x1B => ['Unknown1'],
  0x1C => ['EntityVelocity'],
  0x1D => ['DestroyEntity'],
  0x1E => ['Entity'],
  0x1F => ['EntityRelativeMove'],
  0x20 => ['EntityLook'],
  0x21 => ['EntityLookAndRelativeMove'],
  0x22 => ['EntityTeleport'],
  0x26 => ['EntityStatus'],
  0x27 => ['AttachEntity'],
  0x28 => ['EntityMetadata'],
  0x32 => ['PreChunk'],
  0x33 => ['MapChunk'],
  0x34 => ['MultiBlockChange'],
  0x35 => ['BlockChange'],
  0x36 => ['PlayNoteBlock'],
  0x3C => ['Explosion'],
  0x64 => ['OpenWindow'],
  0x65 => ['CloseWindow'],
  0x66 => ['WindowClick'],
  0x67 => ['SetSlot'],
  0x68 => ['WindowItems'],
  0x69 => ['UpdateProgressBar'],
  0x6A => ['Transaction'],
  0x82 => ['UpdateSign'],
  0xFF => ['Kick'],
}

PACKET_DEFS_REV = Hash[PACKET_DEFS.map{ |k,v| [v[0], k] }]
